Error reporting to server
roboticsware/OpenTyping pull request #12
Opened 2022-06-09 13:55 UTC by camalouu

Added functionality to send errors.log file to server when an exception occurs.

2022-06-13 20:26 UTC, JeongJun-Lee commented
When you make a pr, you have to have your commit only without other's commits. For that you need to create your own work branch for your work only and create a pr from the branch. And because this commit is not for general use, pls make the pr to the globalrank-restful branch, not the dev branch.

2022-06-13 21:27 UTC, JeongJun-Lee requested changes

2022-06-13 21:27 UTC, JeongJun-Lee commented on OpenTyping/App.config
> +	<system.net>
why should this setting be added to the App config?

2022-06-13 21:27 UTC, JeongJun-Lee commented on OpenTyping/ErrorReport.cs
> +            if (File.Exists(errorFile))
The role of a file handling like checking if the file is exist is not and deleting a file this class.  I'll refactor the RestfulProvider class(https://github.com/roboticsware/OpenTyping/blob/globalrank-restful/OpenTyping/RestfulProvider.cs) from WebClient to HttpClient and add new API to report error to the class. After finishing the work, I'll let you know. Then you can just utilize the API for sending the prepared reformatted error with additional info to the server.

2022-06-14 09:31 UTC, JeongJun-Lee commented on OpenTyping/ErrorReport.cs
> +                            $"OS version string: {os.VersionString}\n";
is os version in the platform info different from the value of os variable?

2022-06-15 10:59 UTC, camalouu commented on OpenTyping/App.config
> +	<system.net>
It removes "Expect: 100-continue" header. I don't know why but for some reason program does not send the error file even if it receives the response with 100 status code.

2022-06-16 16:55 UTC, closed without merging